universe   = vanilla
executable = train.sh
output     = output/out/$(Cluster)_$(Process).out
error      = output/err/$(Cluster)_$(Process).err
log        = output/log/$(Cluster)_$(Process).log

MY.WantOS = "el7"
+JobFlavour = "nextweek"
request_gpus            = 1
should_transfer_files = YES
transfer_input_files = codes/checkONNX.py,codes/convertONNX.py,codes/my_mdmm.py,codes/my_mmd.py,codes/my_modules.py,codes/trainRegression_Jet.py
arguments = $(Cluster) $(Process)

queue
