
    universe   = vanilla
    executable = autoSubmissionTemp/epoch1000_tanh800_logit_2/train.sh
    output     = autoSubmissionTemp/epoch1000_tanh800_logit_2/output/output.out
    error      = autoSubmissionTemp/epoch1000_tanh800_logit_2/output/error.err
    log        = autoSubmissionTemp/epoch1000_tanh800_logit_2/output/log.log

    MY.WantOS = "el7"
    +JobFlavour = "espresso"
    request_gpus            = 0
    should_transfer_files = YES
    transfer_input_files = /afs/cern.ch/user/d/dboncukc/fastsim_ref/auto/autoSubmission/autoSubmissionTemp/epoch1000_tanh800_logit_2/checkONNX.py, /afs/cern.ch/user/d/dboncukc/fastsim_ref/auto/autoSubmission/autoSubmissionTemp/epoch1000_tanh800_logit_2/convertONNX.py, /afs/cern.ch/user/d/dboncukc/fastsim_ref/auto/autoSubmission/autoSubmissionTemp/epoch1000_tanh800_logit_2/my_mdmm.py, /afs/cern.ch/user/d/dboncukc/fastsim_ref/auto/autoSubmission/autoSubmissionTemp/epoch1000_tanh800_logit_2/my_mmd.py, /afs/cern.ch/user/d/dboncukc/fastsim_ref/auto/autoSubmission/autoSubmissionTemp/epoch1000_tanh800_logit_2/my_modules.py, /afs/cern.ch/user/d/dboncukc/fastsim_ref/auto/autoSubmission/autoSubmissionTemp/epoch1000_tanh800_logit_2/trainRegression_Jet.py, autoSubmissionTemp/epoch1000_tanh800_logit_2/trainConfig.py
    arguments = $(Cluster) $(Process)
    queue
    