
    universe   = vanilla
    executable = autoSubmissionTemp/epoch1000_tanh800_logit_3/train.sh
    output     = autoSubmissionTemp/epoch1000_tanh800_logit_3/output/output.out
    error      = autoSubmissionTemp/epoch1000_tanh800_logit_3/output/error.err
    log        = autoSubmissionTemp/epoch1000_tanh800_logit_3/output/log.log

    MY.WantOS = "el7"
    +JobFlavour = "espresso"
    request_gpus            = 1
    should_transfer_files = YES
    transfer_input_files = /afs/cern.ch/user/d/dboncukc/fastsim_ref/auto/autoSubmission/autoSubmissionTemp/epoch1000_tanh800_logit_3/checkONNX.py, /afs/cern.ch/user/d/dboncukc/fastsim_ref/auto/autoSubmission/autoSubmissionTemp/epoch1000_tanh800_logit_3/convertONNX.py, /afs/cern.ch/user/d/dboncukc/fastsim_ref/auto/autoSubmission/autoSubmissionTemp/epoch1000_tanh800_logit_3/my_mdmm.py, /afs/cern.ch/user/d/dboncukc/fastsim_ref/auto/autoSubmission/autoSubmissionTemp/epoch1000_tanh800_logit_3/my_mmd.py, /afs/cern.ch/user/d/dboncukc/fastsim_ref/auto/autoSubmission/autoSubmissionTemp/epoch1000_tanh800_logit_3/my_modules.py, /afs/cern.ch/user/d/dboncukc/fastsim_ref/auto/autoSubmission/autoSubmissionTemp/epoch1000_tanh800_logit_3/trainRegression_Jet.py, autoSubmissionTemp/epoch1000_tanh800_logit_3/trainConfig.py
    arguments = $(Cluster) $(Process)
    queue
    